#!/bin/bash

set -e

cd $(dirname $0)

usage() {
    echo "Usage: $0 <operation>"
    echo ""
    echo ""
    echo " Example usage: search for keywords 'untar' and 'zip'"
    echo "    memb untar zip"
    echo ""
    echo " -a <sentence>"
    echo "    Add <sentence> to the knowledge base."
    echo ""
    echo " -p"
    echo "    Print the content of the knowledge base."
    echo ""
    echo " -d <line>"
    echo "    Remove sentence at <line> from the knowledge base."
    echo ""
    exit 1
}

MEMB_FILE=$HOME/.memb
case $1 in
    -a)
        echo $2 >> $MEMB_FILE
        ;;
    -p)
        cat -n $MEMB_FILE
        ;;
    -d)
        re='^[0-9]+$'
        if ! [[ $2 =~ $re ]] ; then
            echo "You have to pass in an integer"; exit 1
        else
            sed --follow-symlinks -i $2d $MEMB_FILE
            echo "Removed line number $2"
        fi
        ;;
    *)
        if [ -z "$1" ]; then
            usage
        else
            grep --color=always -ni "$1" $MEMB_FILE
        fi
esac
