#!/bin/bash

set -e

cd $(dirname $0)

VERSION=0.0.5

usage() {
    echo "Usage: $0 <operation>"
    echo ""
    echo ""
    echo " Example usage: search for keywords 'untar' and 'zip'"
    echo "    memb untar zip"
    echo ""
    echo " -a <sentence>"
    echo "    Add <sentence> to the knowledge base."
    echo ""
    echo " -p"
    echo "    Print the content of the knowledge base."
    echo ""
    echo " -d <line>"
    echo "    Remove sentence at <line> from the knowledge base."
    echo ""
    echo " -v"
    echo "    Print current version."
    echo ""
    exit 1
}

initialize() {
    ENV=${ENV-"PRODUCTION"}
    if [ "$ENV" = "TEST" ] ; then
        MEMB_FILE=./.memb-testfile
    else
        MEMB_FILE=$HOME/.memb
    fi
}

initialize

case $1 in
    -v)
        echo $VERSION
        ;;
    -a)
        echo $2 >> $MEMB_FILE
        ;;
    -p)
        cat -n $MEMB_FILE
        ;;
    -d)
        re='^[0-9]+$'
        if ! [[ $2 =~ $re ]]; then
            echo "You have to pass in an integer"; exit 1
        else
            number_of_lines=$(wc -l < $MEMB_FILE)
            if ((number_of_lines >= $2)); then
                sed --follow-symlinks -i $2d $MEMB_FILE
                echo "Removed line number $2"
            else
                echo "There is no line number $2"
            fi
        fi
        ;;
    *)
        if [ -z "$1" ]; then
            usage
        else
            grep --color=always -ni "$1" $MEMB_FILE
        fi
esac
