#!/bin/bash

set -e

cd $(dirname $0)

echo "Running test suite"
echo ""

export ENV="TEST"
MEMB_FILE=./.memb-testfile

TESTS_RAN=0
# Helpers
assertEq() {
    TESTS_RAN=$((TESTS_RAN+1))
    if [ "$1" -eq "$2" ]; then
        echo "ok"
    else
        echo "failed, expected $2 but got $1"
        tearDown
        exit 1
    fi
}

assertNotEmpty() {
    TESTS_RAN=$((TESTS_RAN+1))
    if [ -z "$1" ]; then
        echo "failed, $1 was expected to be not empty but was empty"
        tearDown
        exit 1
    else
        echo "ok"
    fi
}

tearDown() {
    rm $MEMB_FILE
}

# Tests
echo "add sentence appends sentence"
. ./memb -a "Test sentence"
assertNotEmpty "$(./memb "Test sentence")"
assertNotEmpty "$(./memb "Test")"
assertNotEmpty "$(./memb "TesT")"
assertNotEmpty "$(./memb "TEST")"
assertNotEmpty "$(./memb "ST")"
assertNotEmpty "$(./memb "sT")"

echo "search for existing keyword yields result"
assertEq "$(./memb "Test" | wc -l)" "1"

echo "search for non-existing keyword yields empty result"
assertEq "$(./memb "Foobar" | wc -l)" "0"

echo "delete first line decrements line number"
LINE_NUMBERS_BEFORE=$(./memb "Test sentence" | wc -l)
. ./memb -d 1
LINE_NUMBERS_AFTER=$(./memb "Test sentence" | wc -l)
DIFF=$(expr $LINE_NUMBERS_BEFORE - $LINE_NUMBERS_AFTER)
assertEq "$DIFF" "1"

tearDown

echo "Successfully ran all $TESTS_RAN tests"
exit 0
